version: '3'

services:

  # nestJS backend listening on port 3000
  backend:
    container_name: permissions-service
    build: ./
    volumes:
      - ./src/:/app/src
    ports:
      - 3000:3000
    links:
      - mysql
    command: npm run start:dev

  # mysql service listening on port 3306, username root, password empty
  mysql:
    image: mysql:5.7.12
    container_name: permissions-service-storage
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: permissions
      MYSQL_USER: root
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
