version: '3'

services:

  # nestJS backend listening on port 3000
  backend:
    build: ./backend
    volumes:
      - ./backend/src/:/app/src
    ports:
      - 3000:3000
    links:
      - mysql
    command: npm run start:dev

  # mysql service listening on port 3306, username root, password empty
  mysql:
    image: mysql:5.7.12
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
